### PR TITLE
Update for stackage LTS 8.2

### PR DESCRIPTION
**Pull request by thsutton**
Remove bounds for `optparse-applicative`, fix new warnings in HLint.

### CODE REVIEW

**Comment by jfischoff** [comment]
What is the status of this? Any chance of getting this released ... soon?

**Comment by thsutton** [comment]
Sorry, I'll do it tonight.

**Comment by jfischoff** [comment]
Ah man now I feel bad ... thanks for the lib!

**Comment by thsutton** [comment]
@jfischoff No worries. If you don't prod me it probably won't get done. :-/

**Comment by thsutton** [comment]
@jfischoff FYI I finally opened a PR adding `aeson-diff` and `edit-distance-vector` to stackage nightly an it has been merged; I guess they'll probably be in the next nightly build.

**Pull request merged**
